name: CI

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout monkey_v
      uses: actions/checkout@v2
      with:
        path: vlib/monkey_v
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: Run Tests
      run: |
        cd ./vlib/monkey_v/
        v test .
    - name: Run Main
      run: |
        cd ./vlib/monkey_v/
        for f in examples/*.monkey; do
          echo "=== $f ==="
          v run main.v "$f"
        done

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout monkey_v
      uses: actions/checkout@v2
      with:
        path: vlib/monkey_v
    - name: Build V
      run: |
        make
        ./v symlink
    - name: Run Tests
      run: |
        cd ./vlib/monkey_v/
        v test .
    - name: Run Main
      run: |
        cd ./vlib/monkey_v/
        for f in examples/*.monkey; do
          echo "=== $f ==="
          v run main.v "$f"
        done
